
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.wood_type]

		[types.wood_type.ecologics]
			flowering_azalea = true
			azalea = true
			coconut = true
			walnut = true

		[types.wood_type.architects_palette]
			twisted = true

		[types.wood_type.cataclysm]
			chorus = true

		[types.wood_type.vinery]
			dark_cherry = true

		[types.wood_type.abyssal_decor]
			white_wood = true
			blackwood = true
			cinnamon = true

		[types.wood_type.upgrade_aquatic]
			driftwood = true
			river = true

		[types.wood_type.betterarcheology]
			rotten = true

		[types.wood_type.ad_astra]
			aeronos = true
			strophar = true
			glacian = true

		[types.wood_type.gtceu]
			rubber = true

		[types.wood_type.ars_nouveau]
			archwood = true

		[types.wood_type.thermal]
			rubberwood = true

		[types.wood_type.dimdoors]
			driftwood = true

		[types.wood_type.born_in_chaos_v1]
			scorched = true

		[types.wood_type.forbidden_arcanus]
			fungyss = true
			aurum = true
			edelwood = true

		[types.wood_type.witherstormmod]
			tainted = true

		[types.wood_type.iceandfire]
			dreadwood = true

		[types.wood_type.botania]
			livingwood = true
			dreamwood = true

	[types.leaves_type]

		[types.leaves_type.architects_palette]
			twisted = true

		[types.leaves_type.vinery]
			grapevine = true
			dark_cherry = true
			apple = true

		[types.leaves_type.abyssal_decor]
			cinnamon = true
			flowering_cinnamon = true

		[types.leaves_type.upgrade_aquatic]
			river = true

		[types.leaves_type.ecologics]
			coconut = true
			walnut = true

		[types.leaves_type.ad_astra]
			glacian = true

		[types.leaves_type.gtceu]
			rubber = true

		[types.leaves_type.fruitsdelight]
			pear = true
			hawberry = true
			lychee = true
			mango = true
			persimmon = true
			peach = true
			orange = true
			apple = true
			mangosteen = true
			bayberry = true
			kiwi = true
			fig = true
			durian = true

		[types.leaves_type.ars_nouveau]
			blue_archwood = true
			green_archwood = true
			purple_archwood = true
			red_archwood = true

		[types.leaves_type.thermal]
			rubberwood = true

		[types.leaves_type.occultism]
			otherworld = true

		[types.leaves_type.dimdoors]
			driftwood = true

		[types.leaves_type.forbidden_arcanus]
			aurum = true
			nuggety_aurum = true

		[types.leaves_type.ars_elemental]
			yellow_archwood = true

		[types.leaves_type.witherstormmod]
			tainted = true

	[types.cake]

		[types.cake.thermal]
			chocolate_cake = true
			potion_cake = true
			spice_cake = true

#Disables specific entries
[entries]

	[entries.wood_type]

		[entries.wood_type.storagedrawers]
			full_drawers_2 = true
			half_drawers_1 = true
			full_drawers_4 = true
			half_drawers_4 = true
			trim = true
			half_drawers_2 = true
			full_drawers_1 = true

		[entries.wood_type.architects_palette]
			boards = true
			board_stairs = true
			railing = true
			board_wall = true
			board_slab = true

		[entries.wood_type.create]
			window = true
			window_pane = true

		[entries.wood_type.farmersdelight]
			cabinet = true

